[pytest]
minversion = 7.0
addopts = -v --cov=. --cov-report=xml:coverage.xml --cov-report=term
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning

testpaths = tests
cov_source = .
python_files = *.py
python_classes = *Test*
python_functions = test_*
